### ISSUE TITLE
CircleCi host defined in configuration not used

### ISSUE THREAD

**Issue by AlexRRR** [StackStorm-Exchange/stackstorm-circle_ci#12]
I've noticed that the schema reads 
```yaml
  host:
    description: "Circle CI server host."
    type: "string"
    secret: false
    required: true
    default: "circleci.com"
```    
however, the actions are [hardcoded](https://github.com/StackStorm-Exchange/stackstorm-circle_ci/blob/master/actions/lib/action.py#L36) to use `circleci.com` and not taken from the configuration , I guess this covers most use cases, however for on-site installations this schema is at the very least misleading.

Thanks for sharing your pack, I appreciate the effort.
